// Trainingsplan-Daten: 3er-Split (Ganzkörper A/B/C), Fokus Fettabbau, Fitnessstudio
// increment: Gewichtssteigerung pro Fortschritts-Stufe (kg)
// illus: Schlüssel für die passende Illustration in icons.js

const PLAN = {
  meta: {
    goal: "Fettabbau / Definition",
    location: "Fitnessstudio",
    frequency: "2-3x / Woche",
    deloadEveryNSessions: 12, // ca. alle 4-5 Wochen bei 2-3x/Woche
  },

  days: [
    {
      key: "A",
      label: "Workout A",
      exercises: [
        {
          id: "legpress",
          name: "Beinpresse",
          equipment: "Beinpresse-Maschine (schräge oder liegende Sitzmaschine, Füße auf großer Platte)",
          illus: "leg-press",
          category: "legs-machine",
          sets: 3,
          reps: "10-12",
          rest: 90,
          increment: 5,
        },
        {
          id: "db-bench",
          name: "Kurzhantel-Bankdrücken",
          equipment: "Flachbank + 2 Kurzhanteln",
          illus: "bench-press",
          category: "upper-free",
          sets: 3,
          reps: "8-10",
          rest: 90,
          increment: 2,
        },
        {
          id: "latpulldown",
          name: "Latzug breit",
          equipment: "Kabelturm mit Latzugstange (von oben)",
          illus: "cable-pull-down",
          category: "upper-cable",
          sets: 3,
          reps: "10-12",
          rest: 75,
          increment: 2.5,
        },
        {
          id: "shoulderpress-machine",
          name: "Schulterdrücken Maschine",
          equipment: "Sitzmaschine mit Griffen auf Schulterhöhe, drückt nach oben",
          illus: "machine-press",
          category: "upper-machine",
          sets: 3,
          reps: "10-12",
          rest: 75,
          increment: 2.5,
        },
        {
          id: "plank",
          name: "Plank (Unterarmstütz)",
          equipment: "Matte am Boden",
          illus: "plank-core",
          category: "core",
          sets: 3,
          reps: "40 Sek.",
          rest: 45,
          increment: 0,
          timeBased: true,
          holdSeconds: 40,
        },
        {
          id: "finisher-row",
          name: "Finisher: Rudergerät Intervalle",
          equipment: "Rudergerät (Concept2 o.ä.)",
          illus: "cardio",
          category: "cardio",
          sets: 6,
          reps: "30 Sek. hart / 30 Sek. locker",
          rest: 0,
          increment: 0,
          timeBased: true,
          finisher: true,
          intervalWork: 30,
          intervalRest: 30,
          rounds: 6,
        },
      ],
    },
    {
      key: "B",
      label: "Workout B",
      exercises: [
        {
          id: "legcurl",
          name: "Beinbeuger liegend",
          equipment: "Liegende oder sitzende Beinbeuger-Maschine (Polster hinter der Wade)",
          illus: "leg-curl",
          category: "legs-machine",
          sets: 3,
          reps: "10-12",
          rest: 75,
          increment: 5,
        },
        {
          id: "seated-row",
          name: "Rudern sitzend (Kabelzug)",
          equipment: "Kabelzug niedrig mit V-Griff oder Stange, Fußstützen",
          illus: "cable-row",
          category: "upper-cable",
          sets: 3,
          reps: "10-12",
          rest: 75,
          increment: 2.5,
        },
        {
          id: "legextension",
          name: "Beinstrecker",
          equipment: "Sitzmaschine, Polster vor dem Schienbein, streckt das Knie",
          illus: "leg-extension",
          category: "legs-machine",
          sets: 3,
          reps: "10-12",
          rest: 75,
          increment: 5,
        },
        {
          id: "latpulldown-close",
          name: "Latzug eng (enger Griff)",
          equipment: "Kabelturm mit V-Griff oder engem Griff (von oben)",
          illus: "cable-pull-down",
          category: "upper-cable",
          sets: 3,
          reps: "10-12",
          rest: 75,
          increment: 2.5,
        },
        {
          id: "cable-curl",
          name: "Bizeps Kabel-Curl",
          equipment: "Kabelzug niedrig mit gerader oder EZ-Stange",
          illus: "cable-curl",
          category: "arms",
          sets: 3,
          reps: "10-12",
          rest: 60,
          increment: 2,
        },
        {
          id: "finisher-bike",
          name: "Finisher: Crosstrainer Intervalle",
          equipment: "Crosstrainer",
          illus: "cardio",
          category: "cardio",
          sets: 6,
          reps: "30 Sek. hart / 30 Sek. locker",
          rest: 0,
          increment: 0,
          timeBased: true,
          finisher: true,
          intervalWork: 30,
          intervalRest: 30,
          rounds: 6,
        },
      ],
    },
    {
      key: "C",
      label: "Workout C",
      exercises: [
        {
          id: "goblet-squat",
          name: "Kurzhantel Goblet Squat",
          equipment: "Eine Kurzhantel, senkrecht vor der Brust gehalten",
          illus: "goblet-squat",
          category: "upper-free",
          sets: 3,
          reps: "10-12",
          rest: 90,
          increment: 2,
        },
        {
          id: "chest-press-machine",
          name: "Brustpresse Maschine",
          equipment: "Sitzmaschine mit Griffen auf Brusthöhe, drückt nach vorn",
          illus: "machine-press",
          category: "upper-machine",
          sets: 3,
          reps: "10-12",
          rest: 75,
          increment: 2.5,
        },
        {
          id: "back-extension",
          name: "Rückenstrecker (Hyperextension)",
          equipment: "Schrägbank mit Fußhalterung, Oberkörper hängt vorn über",
          illus: "back-extension",
          category: "core",
          sets: 3,
          reps: "12-15",
          rest: 60,
          increment: 0,
        },
        {
          id: "triceps-pushdown",
          name: "Trizeps Kabel-Pushdown",
          equipment: "Kabelturm mit Stange oder Seil (von oben nach unten drücken)",
          illus: "cable-pushdown",
          category: "arms",
          sets: 3,
          reps: "10-12",
          rest: 60,
          increment: 2,
        },
        {
          id: "lateral-raise",
          name: "Seitheben Kurzhantel",
          equipment: "2 leichte Kurzhanteln, freistehend",
          illus: "lateral-raise",
          category: "upper-free-light",
          sets: 3,
          reps: "12-15",
          rest: 60,
          increment: 1,
        },
        {
          id: "finisher-cardio",
          name: "Finisher: Laufband/Crosstrainer Intervalle",
          equipment: "Laufband oder Crosstrainer",
          illus: "cardio",
          category: "cardio",
          sets: 6,
          reps: "30 Sek. hart / 30 Sek. locker",
          rest: 0,
          increment: 0,
          timeBased: true,
          finisher: true,
          intervalWork: 30,
          intervalRest: 30,
          rounds: 6,
        },
      ],
    },
  ],
};
